---


- name: Copy Stack | Create docker stack directory
  file:
    state: directory
    path: "{{ kafka_docker_stack_directory }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0700'


- name: Copy Stack | Copy docker stack
  copy:
    src: files/docker_stack/
    dest: "{{ kafka_docker_stack_directory }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0700'